{
 "title": "Artemis View",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pods",
    "label": "Pods",
    "query": "label_values(artemis_clustered,pod)"
   },
   {
    "name": "address",
    "label": "Address",
    "query": "label_values(artemis_messages_acknowledged{pod=\"$pods\",address!~\"^\\\\$.*\"},address)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Cluster Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(artemis_clustered{}) by (instance))"
    }
   ]
  },
  {
   "title": "Master Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(artemis_clustered{pod=~\"(.*)master(.*)\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Longest Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 1 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(artemis_uptime_millis{address!~\"^\\\\$.*\"})"
    }
   ]
  },
  {
   "title": "Slave Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(artemis_clustered{pod=~\"(.*)slave(.*)\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Last Restart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 3 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    { "expr": "min(artemis_uptime_millis)" }
   ]
  },
  {
   "title": "Active Cluster Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(artemis_uptime_millis{address!~\"^\\\\$.*\",job!~\"(.*)master(.*)\",job!~\"(.*)slave(.*)\"}) by (pod)"
    },
    {
     "expr": "max(kube_pod_container_status_restarts_total{pod=~\".*activemq-artemis.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Message Statistics (Clustered)",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(artemis_messages_added{address!~\"^\\\\$.*\",queue!=\"\"}) by (address)",
     "legendFormat": "Enqueued"
    },
    {
     "expr": "sum(artemis_messages_acknowledged{address!~\"^\\\\$.*\",queue!=\"\"}) by (address)",
     "legendFormat": "Dequeued"
    },
    {
     "expr": "sum(artemis_messages_expired{address!~\"^\\\\$.*\",queue!=\"\"}) by (address)"
    },
    {
     "expr": "sum(artemis_consumer_count{address!~\"^\\\\$.*\",queue!=\"\"}) by (address)"
    },
    {
     "expr": "sum(rate(artemis_messages_acknowledged{address!~\"^\\\\$.*\",queue!=\"\"}[5m])) by (address)"
    }
   ]
  },
  { "title": "Instance View for $pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Start State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_status_running{pod=\"$pods\"}"
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(artemis_total_messages_acknowledged{pod=\"$pods\"}[1m])"
    }
   ]
  },
  {
   "title": "Address Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "artemis_address_memory_usage_percentage{pod=\"$pods\"}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 19 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=\"$pods\"}"
    }
   ]
  },
  {
   "title": "Ready State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{pod=\"$pods\"}"
    }
   ]
  },
  {
   "title": "Instance Message Statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(artemis_messages_added{address!~\"^\\\\$.*\",queue!=\"\",pod=\"$pods\"}) by (address)"
    },
    {
     "expr": "sum(artemis_messages_acknowledged{address!~\"^\\\\$.*\",queue!=\"\",pod=\"$pods\"}) by (address)"
    },
    {
     "expr": "sum(artemis_messages_expired{address!~\"^\\\\$.*\",queue!=\"\",pod=\"$pods\"}) by (address)"
    },
    {
     "expr": "sum(artemis_consumer_count{address!~\"^\\\\$.*\",queue!=\"\",pod=\"$pods\"}) by (address)"
    },
    {
     "expr": "sum(rate(artemis_messages_acknowledged{address!~\"^\\\\$.*\",queue!=\"\",pod=\"$pods\"}[5m])) by (address)"
    }
   ]
  },
  {
   "title": "Address View for $address on $pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Message Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "messages per second" }
   ],
   "targets": [
    {
     "expr": "rate(artemis_messages_acknowledged{pod=\"$pods\",address=\"$address\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}